/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void pol_spu_func_00000A00(spu_context* ctx);
void pol_spu_func_00000A2C(spu_context* ctx);
void pol_spu_func_00000A30(spu_context* ctx);
void pol_spu_func_00000A38(spu_context* ctx);
void pol_spu_func_00000A5C(spu_context* ctx);
void pol_spu_func_00000AB8(spu_context* ctx);
void pol_spu_func_00000BAC(spu_context* ctx);
void pol_spu_func_00000C38(spu_context* ctx);
void pol_spu_func_00000CA4(spu_context* ctx);
void pol_spu_func_00000CA8(spu_context* ctx);
void pol_spu_func_00000CD4(spu_context* ctx);
void pol_spu_func_000010F4(spu_context* ctx);
void pol_spu_func_000010F8(spu_context* ctx);
void pol_spu_func_000010FC(spu_context* ctx);
void pol_spu_func_00001140(spu_context* ctx);
void pol_spu_func_00001158(spu_context* ctx);
void pol_spu_func_00001190(spu_context* ctx);
void pol_spu_func_000011E8(spu_context* ctx);
void pol_spu_func_00001210(spu_context* ctx);
void pol_spu_func_000012D0(spu_context* ctx);
void pol_spu_func_0000138C(spu_context* ctx);
void pol_spu_func_0000139C(spu_context* ctx);
void pol_spu_func_000013A4(spu_context* ctx);
void pol_spu_func_000013E0(spu_context* ctx);
void pol_spu_func_00001450(spu_context* ctx);
void pol_spu_func_000014C0(spu_context* ctx);
void pol_spu_func_00001534(spu_context* ctx);
void pol_spu_func_0000156C(spu_context* ctx);
void pol_spu_func_0000158C(spu_context* ctx);
void pol_spu_func_000015A4(spu_context* ctx);
void pol_spu_func_000015C8(spu_context* ctx);
void pol_spu_func_000015E0(spu_context* ctx);
void pol_spu_func_000016AC(spu_context* ctx);
void pol_spu_func_000016E8(spu_context* ctx);
void pol_spu_func_00001790(spu_context* ctx);
void pol_spu_func_000017DC(spu_context* ctx);
void pol_spu_func_0000183C(spu_context* ctx);
void pol_spu_func_00001908(spu_context* ctx);
void pol_spu_func_00001954(spu_context* ctx);
void pol_spu_func_00001968(spu_context* ctx);
void pol_spu_func_000019C8(spu_context* ctx);
void pol_spu_func_00001A7C(spu_context* ctx);
void pol_spu_func_00001AC8(spu_context* ctx);
void pol_spu_func_00001AE0(spu_context* ctx);
void pol_spu_func_00001B30(spu_context* ctx);
void pol_spu_func_00001BE0(spu_context* ctx);
void pol_spu_func_00001D68(spu_context* ctx);
void pol_spu_func_00001DE4(spu_context* ctx);
void pol_spu_func_00001EC4(spu_context* ctx);
void pol_spu_func_00001EF8(spu_context* ctx);
void pol_spu_func_0000209C(spu_context* ctx);
void pol_spu_func_000020A4(spu_context* ctx);
void pol_spu_func_00002104(spu_context* ctx);
void pol_spu_func_00002124(spu_context* ctx);
void pol_spu_func_00002140(spu_context* ctx);
void pol_spu_func_00002188(spu_context* ctx);
void pol_spu_func_000021E4(spu_context* ctx);
void pol_spu_func_000021FC(spu_context* ctx);
void pol_spu_func_0000220C(spu_context* ctx);
void pol_spu_func_0000227C(spu_context* ctx);
void pol_spu_func_00002354(spu_context* ctx);
void pol_spu_func_000023AC(spu_context* ctx);
void pol_spu_func_000023E8(spu_context* ctx);
void pol_spu_func_00002458(spu_context* ctx);
void pol_spu_func_00002514(spu_context* ctx);
void pol_spu_func_00002580(spu_context* ctx);
void pol_spu_func_00002610(spu_context* ctx);
void pol_spu_func_00002684(spu_context* ctx);
void pol_spu_func_00002724(spu_context* ctx);
void pol_spu_func_00002768(spu_context* ctx);
void pol_spu_func_00002774(spu_context* ctx);
void pol_spu_func_00002810(spu_context* ctx);
void pol_spu_func_00002830(spu_context* ctx);
void pol_spu_func_00002848(spu_context* ctx);
void pol_spu_func_00002888(spu_context* ctx);
void pol_spu_func_000028B0(spu_context* ctx);
void pol_spu_func_00002990(spu_context* ctx);
void pol_spu_func_00002998(spu_context* ctx);
void pol_spu_func_000029D8(spu_context* ctx);
void pol_spu_func_000029E0(spu_context* ctx);
void pol_spu_func_00002A20(spu_context* ctx);
void pol_spu_func_00002A38(spu_context* ctx);
void pol_spu_func_00002A40(spu_context* ctx);
void pol_spu_func_00002A78(spu_context* ctx);
void pol_spu_func_00002A88(spu_context* ctx);
void pol_spu_func_00002A90(spu_context* ctx);
void pol_spu_func_00002A98(spu_context* ctx);
void pol_spu_func_00002AD0(spu_context* ctx);
void pol_spu_func_00002B60(spu_context* ctx);
void pol_spu_func_00002B70(spu_context* ctx);
void pol_spu_func_00002B90(spu_context* ctx);
void pol_spu_func_00002D40(spu_context* ctx);
void pol_spu_func_00002E20(spu_context* ctx);
void pol_spu_func_00003020(spu_context* ctx);
void pol_spu_func_00003040(spu_context* ctx);
void pol_spu_func_00003214(spu_context* ctx);
void pol_spu_func_00003220(spu_context* ctx);
void pol_spu_func_00003260(spu_context* ctx);
void pol_spu_func_00003294(spu_context* ctx);
void pol_spu_func_00003298(spu_context* ctx);
void pol_spu_func_000032A0(spu_context* ctx);
void pol_spu_func_000032D0(spu_context* ctx);
void pol_spu_func_00003384(spu_context* ctx);
void pol_spu_func_00003388(spu_context* ctx);
void pol_spu_func_000033C8(spu_context* ctx);
void pol_spu_func_000033D0(spu_context* ctx);
void pol_spu_func_000033D4(spu_context* ctx);
void pol_spu_func_00003424(spu_context* ctx);
void pol_spu_func_0000346C(spu_context* ctx);
void pol_spu_func_000034E8(spu_context* ctx);
void pol_spu_func_00003510(spu_context* ctx);
void pol_spu_func_00003518(spu_context* ctx);
void pol_spu_func_00003530(spu_context* ctx);
void pol_spu_func_00003568(spu_context* ctx);
void pol_spu_func_00003590(spu_context* ctx);
void pol_spu_func_00003618(spu_context* ctx);
void pol_spu_func_000036B0(spu_context* ctx);
void pol_spu_func_00003800(spu_context* ctx);
void pol_spu_func_0000390C(spu_context* ctx);
void pol_spu_func_00003928(spu_context* ctx);
void pol_spu_func_00003958(spu_context* ctx);
void pol_spu_func_00003AB0(spu_context* ctx);
void pol_spu_func_00003AD0(spu_context* ctx);
void pol_spu_func_00003B00(spu_context* ctx);
void pol_spu_func_00003B34(spu_context* ctx);
void pol_spu_func_00003B90(spu_context* ctx);
void pol_spu_func_00003C9C(spu_context* ctx);
void pol_spu_func_00003D08(spu_context* ctx);
void pol_spu_func_00003D10(spu_context* ctx);
void pol_spu_func_00003DE4(spu_context* ctx);
void pol_spu_func_00003E20(spu_context* ctx);
void pol_spu_func_00003E30(spu_context* ctx);
void pol_spu_func_00003E38(spu_context* ctx);
void pol_spu_func_00003E64(spu_context* ctx);
void pol_spu_func_00003E78(spu_context* ctx);
void pol_spu_func_00003EDC(spu_context* ctx);
void pol_spu_func_00003F04(spu_context* ctx);
void pol_spu_func_00004010(spu_context* ctx);
void pol_spu_func_00004020(spu_context* ctx);
void pol_spu_func_00004028(spu_context* ctx);
void pol_spu_func_00004078(spu_context* ctx);
void pol_spu_func_0000407C(spu_context* ctx);
void pol_spu_func_00004084(spu_context* ctx);
void pol_spu_func_00004090(spu_context* ctx);
void pol_spu_func_000040A8(spu_context* ctx);
void pol_spu_func_000040F8(spu_context* ctx);
void pol_spu_func_000041CC(spu_context* ctx);
void pol_spu_func_000042FC(spu_context* ctx);
void pol_spu_func_00004384(spu_context* ctx);
void pol_spu_func_000043F8(spu_context* ctx);
void pol_spu_func_00004418(spu_context* ctx);
void pol_spu_func_00004448(spu_context* ctx);
void pol_spu_func_00004450(spu_context* ctx);
void pol_spu_func_00004458(spu_context* ctx);
void pol_spu_func_00004474(spu_context* ctx);
void pol_spu_func_00004480(spu_context* ctx);
void pol_spu_func_0000448C(spu_context* ctx);
void pol_spu_func_00004494(spu_context* ctx);
void pol_spu_func_000044E8(spu_context* ctx);
void pol_spu_func_00004500(spu_context* ctx);
void pol_spu_func_00004540(spu_context* ctx);
void pol_spu_func_00004568(spu_context* ctx);
void pol_spu_func_00004644(spu_context* ctx);
void pol_spu_func_00004720(spu_context* ctx);
void pol_spu_func_0000473C(spu_context* ctx);
void pol_spu_func_000047C0(spu_context* ctx);

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void pol_spu_recomp_register(void);
